spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        ddl-auto: update
        jdbc:
          lob:
            non_contextual_creation: true
      properties:
        higernate:
          temp:
            use_jdbc_metadata_defaults: false
    open-in-view: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
server:
  port: 8080
fe_url: http://localhost:4200
be_url: http://localhost:8080

