spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
#    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:~/test/testdb
    username: sa
    password: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  server:
  port: 8080
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
