insert into user (email, nickname, password, role) values  ('admin@blog.com', 'admin', '$2a$10$avE8qwumKFF2fixM4FqiiuG/LKj1qg1PH.FJj7t42EAaT776thBf6', 'ROLE_ADMIN');
insert into user (email, nickname, password, role) values  ('writer@blog.com', 'writer', '$2a$10$avE8qwumKFF2fixM4FqiiuG/LKj1qg1PH.FJj7t42EAaT776thBf6', 'ROLE_WRITER');
insert into user (email, nickname, password, role) values  ('user@blog.com', 'user', '$2a$10$avE8qwumKFF2fixM4FqiiuG/LKj1qg1PH.FJj7t42EAaT776thBf6', 'ROLE_USER');
insert into category (name) values ('Monitory');
insert into category (name) values ('Komputer');
insert into category (name) values ('Laptopy');
insert into post (create_date, modified_date, text, title, posts_categories, posts_users) VALUES (GETDATE(), GETDATE(), '

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam fringilla augue et posuere congue. Ut efficitur ligula sit amet augue accumsan luctus et quis massa. Fusce venenatis augue nec venenatis facilisis. Praesent efficitur lectus et nulla elementum fringilla. Cras ornare nulla eget dapibus sodales. Morbi vitae magna ante. Donec laoreet, ipsum quis varius iaculis, purus nunc pellentesque purus, vel scelerisque odio elit eu enim. Suspendisse in odio aliquam, rhoncus lectus a, posuere ipsum. Duis ut convallis eros, non porta lacus. Nullam sagittis fringilla neque sit amet vestibulum. Quisque vitae quam nec diam placerat commodo eget at nisi. Pellentesque ultrices, est a tempor gravida, est augue fermentum odio, vel suscipit ante libero vel metus.

Nulla placerat metus ut mi pretium, sit amet interdum odio condimentum. Nunc a purus nec quam blandit efficitur quis id nisi. Pellentesque nunc mauris, lacinia at urna at, sollicitudin vehicula massa. Mauris id dolor urna. Quisque ullamcorper fermentum erat. Donec laoreet libero quis egestas elementum. Cras venenatis suscipit dolor, sit amet tempus tellus scelerisque vitae. Quisque vestibulum mi purus, eu sodales mi iaculis sit amet. Suspendisse gravida purus ac purus semper, id luctus sapien porta. Duis scelerisque luctus lorem mollis aliquet. Etiam maximus lacinia massa, ac scelerisque mi sodales non. Phasellus quis lacus quis ex posuere hendrerit sit amet et sapien. Ut non erat imperdiet, tempor nisl id, condimentum magna. Praesent interdum scelerisque purus a elementum. Maecenas ut urna ac lectus luctus mollis nec ut erat.

Aenean aliquet quam quis leo consectetur sodales. Morbi pellentesque viverra ex, et congue velit maximus eu. Vivamus dapibus scelerisque neque nec convallis. Sed tincidunt metus non iaculis imperdiet. Suspendisse volutpat porta arcu, ac tincidunt leo lobortis at. Ut libero nulla, lacinia ac velit vel, dignissim aliquet odio. Donec metus nibh, bibendum vel eros quis, varius cursus mi. Nam aliquet sollicitudin nisl hendrerit dictum. Mauris accumsan dolor posuere leo laoreet aliquam. Vestibulum et lacinia mi. Vestibulum metus metus, porttitor sed accumsan in, elementum a libero. Fusce risus orci, convallis a lorem non, lobortis mollis ex. Proin lacinia mollis fermentum.

Nunc volutpat orci at turpis euismod, in condimentum leo facilisis. Duis sodales ex non sem vulputate, nec tincidunt magna ultricies. Duis imperdiet tincidunt lorem, id hendrerit mauris blandit id. Vivamus rutrum at dui nec fermentum. Proin ac vehicula odio. Nunc eu urna a elit convallis blandit. Vestibulum a odio elit. Quisque sem diam, malesuada eget tincidunt a, feugiat in lectus. Suspendisse mi justo, semper eget lobortis sed, lacinia eu eros. Sed id mi in massa volutpat ornare vel commodo justo. Sed consequat mauris elit, sed euismod arcu sollicitudin nec. Suspendisse massa purus, fringilla et imperdiet vehicula, faucibus vitae ipsum.

Donec in orci vel leo tempus elementum. Suspendisse dictum ultricies varius. Aliquam finibus suscipit nisi, in pretium erat ornare vitae. Ut tempus lacinia odio, non bibendum augue tristique quis. Quisque dapibus, est nec interdum suscipit, risus augue aliquet ipsum, non tristique augue neque eget massa. Mauris nunc tellus, ornare venenatis ultricies vitae, maximus rhoncus ex. Nunc quis aliquet ante. ',
 'Nowe monitory', 1, 2);

 insert into post (create_date, modified_date, text, title, posts_categories, posts_users) VALUES (GETDATE(), GETDATE(), '

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam fringilla augue et posuere congue. Ut efficitur ligula sit amet augue accumsan luctus et quis massa. Fusce venenatis augue nec venenatis facilisis. Praesent efficitur lectus et nulla elementum fringilla. Cras ornare nulla eget dapibus sodales. Morbi vitae magna ante. Donec laoreet, ipsum quis varius iaculis, purus nunc pellentesque purus, vel scelerisque odio elit eu enim. Suspendisse in odio aliquam, rhoncus lectus a, posuere ipsum. Duis ut convallis eros, non porta lacus. Nullam sagittis fringilla neque sit amet vestibulum. Quisque vitae quam nec diam placerat commodo eget at nisi. Pellentesque ultrices, est a tempor gravida, est augue fermentum odio, vel suscipit ante libero vel metus.

Nulla placerat metus ut mi pretium, sit amet interdum odio condimentum. Nunc a purus nec quam blandit efficitur quis id nisi. Pellentesque nunc mauris, lacinia at urna at, sollicitudin vehicula massa. Mauris id dolor urna. Quisque ullamcorper fermentum erat. Donec laoreet libero quis egestas elementum. Cras venenatis suscipit dolor, sit amet tempus tellus scelerisque vitae. Quisque vestibulum mi purus, eu sodales mi iaculis sit amet. Suspendisse gravida purus ac purus semper, id luctus sapien porta. Duis scelerisque luctus lorem mollis aliquet. Etiam maximus lacinia massa, ac scelerisque mi sodales non. Phasellus quis lacus quis ex posuere hendrerit sit amet et sapien. Ut non erat imperdiet, tempor nisl id, condimentum magna. Praesent interdum scelerisque purus a elementum. Maecenas ut urna ac lectus luctus mollis nec ut erat.

Aenean aliquet quam quis leo consectetur sodales. Morbi pellentesque viverra ex, et congue velit maximus eu. Vivamus dapibus scelerisque neque nec convallis. Sed tincidunt metus non iaculis imperdiet. Suspendisse volutpat porta arcu, ac tincidunt leo lobortis at. Ut libero nulla, lacinia ac velit vel, dignissim aliquet odio. Donec metus nibh, bibendum vel eros quis, varius cursus mi. Nam aliquet sollicitudin nisl hendrerit dictum. Mauris accumsan dolor posuere leo laoreet aliquam. Vestibulum et lacinia mi. Vestibulum metus metus, porttitor sed accumsan in, elementum a libero. Fusce risus orci, convallis a lorem non, lobortis mollis ex. Proin lacinia mollis fermentum.

Nunc volutpat orci at turpis euismod, in condimentum leo facilisis. Duis sodales ex non sem vulputate, nec tincidunt magna ultricies. Duis imperdiet tincidunt lorem, id hendrerit mauris blandit id. Vivamus rutrum at dui nec fermentum. Proin ac vehicula odio. Nunc eu urna a elit convallis blandit. Vestibulum a odio elit. Quisque sem diam, malesuada eget tincidunt a, feugiat in lectus. Suspendisse mi justo, semper eget lobortis sed, lacinia eu eros. Sed id mi in massa volutpat ornare vel commodo justo. Sed consequat mauris elit, sed euismod arcu sollicitudin nec. Suspendisse massa purus, fringilla et imperdiet vehicula, faucibus vitae ipsum.

Donec in orci vel leo tempus elementum. Suspendisse dictum ultricies varius. Aliquam finibus suscipit nisi, in pretium erat ornare vitae. Ut tempus lacinia odio, non bibendum augue tristique quis. Quisque dapibus, est nec interdum suscipit, risus augue aliquet ipsum, non tristique augue neque eget massa. Mauris nunc tellus, ornare venenatis ultricies vitae, maximus rhoncus ex. Nunc quis aliquet ante. ',
 'Laptop a bateria', 3, 2);

 insert into post (create_date, modified_date, text, title, posts_categories, posts_users) VALUES (GETDATE(), GETDATE(), '

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam fringilla augue et posuere congue. Ut efficitur ligula sit amet augue accumsan luctus et quis massa. Fusce venenatis augue nec venenatis facilisis. Praesent efficitur lectus et nulla elementum fringilla. Cras ornare nulla eget dapibus sodales. Morbi vitae magna ante. Donec laoreet, ipsum quis varius iaculis, purus nunc pellentesque purus, vel scelerisque odio elit eu enim. Suspendisse in odio aliquam, rhoncus lectus a, posuere ipsum. Duis ut convallis eros, non porta lacus. Nullam sagittis fringilla neque sit amet vestibulum. Quisque vitae quam nec diam placerat commodo eget at nisi. Pellentesque ultrices, est a tempor gravida, est augue fermentum odio, vel suscipit ante libero vel metus.

Nulla placerat metus ut mi pretium, sit amet interdum odio condimentum. Nunc a purus nec quam blandit efficitur quis id nisi. Pellentesque nunc mauris, lacinia at urna at, sollicitudin vehicula massa. Mauris id dolor urna. Quisque ullamcorper fermentum erat. Donec laoreet libero quis egestas elementum. Cras venenatis suscipit dolor, sit amet tempus tellus scelerisque vitae. Quisque vestibulum mi purus, eu sodales mi iaculis sit amet. Suspendisse gravida purus ac purus semper, id luctus sapien porta. Duis scelerisque luctus lorem mollis aliquet. Etiam maximus lacinia massa, ac scelerisque mi sodales non. Phasellus quis lacus quis ex posuere hendrerit sit amet et sapien. Ut non erat imperdiet, tempor nisl id, condimentum magna. Praesent interdum scelerisque purus a elementum. Maecenas ut urna ac lectus luctus mollis nec ut erat.

Aenean aliquet quam quis leo consectetur sodales. Morbi pellentesque viverra ex, et congue velit maximus eu. Vivamus dapibus scelerisque neque nec convallis. Sed tincidunt metus non iaculis imperdiet. Suspendisse volutpat porta arcu, ac tincidunt leo lobortis at. Ut libero nulla, lacinia ac velit vel, dignissim aliquet odio. Donec metus nibh, bibendum vel eros quis, varius cursus mi. Nam aliquet sollicitudin nisl hendrerit dictum. Mauris accumsan dolor posuere leo laoreet aliquam. Vestibulum et lacinia mi. Vestibulum metus metus, porttitor sed accumsan in, elementum a libero. Fusce risus orci, convallis a lorem non, lobortis mollis ex. Proin lacinia mollis fermentum.

Nunc volutpat orci at turpis euismod, in condimentum leo facilisis. Duis sodales ex non sem vulputate, nec tincidunt magna ultricies. Duis imperdiet tincidunt lorem, id hendrerit mauris blandit id. Vivamus rutrum at dui nec fermentum. Proin ac vehicula odio. Nunc eu urna a elit convallis blandit. Vestibulum a odio elit. Quisque sem diam, malesuada eget tincidunt a, feugiat in lectus. Suspendisse mi justo, semper eget lobortis sed, lacinia eu eros. Sed id mi in massa volutpat ornare vel commodo justo. Sed consequat mauris elit, sed euismod arcu sollicitudin nec. Suspendisse massa purus, fringilla et imperdiet vehicula, faucibus vitae ipsum.

Donec in orci vel leo tempus elementum. Suspendisse dictum ultricies varius. Aliquam finibus suscipit nisi, in pretium erat ornare vitae. Ut tempus lacinia odio, non bibendum augue tristique quis. Quisque dapibus, est nec interdum suscipit, risus augue aliquet ipsum, non tristique augue neque eget massa. Mauris nunc tellus, ornare venenatis ultricies vitae, maximus rhoncus ex. Nunc quis aliquet ante. ',
 'Komputery dla graczy', 2, 2);